- name: Install prerequisite packages
  apt:
    name:
      - libpq-dev
      - linux-libc-dev
      - libc6-dev
    state: present
    update_cache: yes

# curl -SL https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose

- name: Get binary
  uri:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "u+x,g+x,o+x"


- name: Create symbolic link
  file:
    src:  /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link

# curl \
#  -X POST \
#  -H "Accept: application/vnd.github+json" \
#  -H "Authorization: token <TOKEN>" \
#  https://api.github.com/repos/OWNER/REPO/actions/runners/registration-token
- name: Get token for runner
  uri:
    url: https://api.github.com/repos/{{github_owner}}/{{github_repo}}/actions/runners/registration-token
    method: POST
    headers:
      Accept: application/vnd.github+json
      Authorization: token {{github_authtoken}}
    status_code: 201
  register: runner_token


# curl -o actions-runner-linux-x64-2.295.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.295.0/actions-runner-linux-x64-2.295.0.tar.gz

- name: Get binary runner
  uri:
    url: https://github.com/actions/runner/releases/download/v2.295.0/actions-runner-linux-x64-2.295.0.tar.gz
    follow_redirects: all
    dest: /tmp/actions-runner-linux-x64-2.295.0.tar.gz


- name: Create a directory if it does not exist
  become: no
  file:
    path: actions-runner
    state: directory

- name: Unarchive a file that needs to be downloaded
  become: no
  shell: tar -xf /tmp/actions-runner-linux-x64-2.295.0.tar.gz
  args:
    chdir: actions-runner

# - debug:
#     var: runner_token

- name: Configure runner
  become: no
  shell: ./config.sh --url https://github.com/{{github_owner}}/{{github_repo}} --token {{runner_token.json.token}} --name vkcs --runnergroup default --labels self-hosted,vkcs --work _work
  args:
    chdir: actions-runner

- name: Install service
  shell: ./svc.sh install
  args:
    chdir: actions-runner

- name: Start service
  service:
    name: actions.runner.{{github_owner}}-{{github_repo}}.vkcs.service
    state: started
