name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  POSTGRES_DB: "appdb" 
  POSTGRES_USER: "app_user"
  POSTGRES_PASSWORD: "${{ secrets.PostgresPass }}"

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: "windblow"
        password: ${{ secrets.DOCKERHUBPASS }}
    - name: "Build docker container"
      run: |
        docker build . -t windblow/django_example:$GITHUB_SHA 
        docker push windblow/django_example:$GITHUB_SHA 
    - name: "Execute tests in container"
      run: |
        docker run windblow/django_example:$GITHUB_SHA python manage.py test
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: "Deploy"
      run: |
        source .github/prod_env        
        echo "POSTGRES_DB=$POSTGRES_DB" >> .env
        echo "POSTGRES_USER=$POSTGRES_USER" >> .env
        echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
        echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env
        docker-compose build
        docker-compose up -d
      env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRESPASS }}
