- name: Install nginx
  apt:
    update_cache: true
    name: nginx
    state: present
- name: Copy config
  copy:
    src: ../configs/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Retart nginx

- name: Copy django directories
  copy:
    src: ../../../../{{item}} # files
    dest: ~/src/
  with_items:
    - pages
    - django_project
  tags:
    - copy

- name: Copy django files
  copy:
    src: ../../../../{{item}}
    dest: ~/src/{{item}}
  with_items:
    - Dockerfile
    - manage.py
    - requirements.txt
  tags:
    - copy

- name: Copy docker-compose file
  copy:
    src: ../../../../docker-compose.dev.yml
    dest: ~/src/docker-compose.yml
  tags:
    - copy

- name: Create and start django services
  community.docker.docker_compose_v2:
    project_src: ~/src
    build: always
  register: output
  tags:
    - run
